#!/bin/bash
#set -x
#set -e

DOTCONF=$HOME/.conf

BootstrapPlatform() {
  pushd $DOTCONF > /dev/null
  git remote set-url origin git@github.com:harsla/.conf.git
  popd > /dev/null
  MY_DOTFILES=$DOTCONF/dotfiles
  MY_BINS=$DOTCONF/bin
  source $DOTCONF/platform/$1/bootstrap.sh
}

DeterminePlatform() {
  PLATFORM="unknown"
  case `uname` in
    Linux)
      if [ -f /etc/arch-release ] ; then
        PLATFORM="archlinux"
      elif [ -f /etc/lsb-release ]; then
        if grep "Microsoft" /proc/sys/kernel/osrelease; then
          PLATFORM="wsl"
        else
          PLATFORM="ubuntu"
        fi
      elif grep "Raspbian" /etc/issue; then
        PLATFORM="raspbian"
      fi
      ;;
    Darwin)
      PLATFORM="darwin"
      ;;
    MINGW*)
      PLATFORM="win"
      ;;
    CYGWIN*)
      PLATFORM="win"
      ;;
  esac
  if [ "$PLATFORM" = "unknown" ]; then
    echo "Unknown platform!"
    return -1
  else
    echo "Platform: $PLATFORM"
  fi
}

UpdatePackageManagers() {
  case $PLATFORM in 
    archlinux)
      echo "Invoking pacman to synchronize package list"
      sudo pacman -Sy
      return $?
      ;;
    ubuntu|wsl|raspbian)
      echo "Updating apt packages ..."
      AptUpdatedToday || UpdateAptRepositories
      return $?
      ;;
    darwin)
      if hash brew > /dev/null 2>&1; then
        echo "Updating brew packages ..."
        brew update
        echo "Installing oh-my-zsh"
        ruby -e "$(wget --no-check-certificate https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh)"
        echo "Set Default Shell"
        ruby -e "$(chsh -s `which zsh`)"
        echo "Set ZSH Theme"
        ruby -e "$(cd .oh-my-zsh/themes/ && wget --no-check-certificate  https://raw.githubusercontent.com/babun/babun/master/babun-core/plugins/oh-my-zsh/src/babun.zsh-theme)"
      else
        echo "Installing brew"
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      fi
      return $?
      ;;
  esac
}

RequirePackage() {
  hash $1 >/dev/null 2>&1 || {
    case $PLATFORM in 
      archlinux)
        sudo pacman -S $1
        return $?
        ;;
      ubuntu|raspbian)
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y $1
        return $?
        ;;
      darwin)
        brew install -y $1
        return $?
        ;;
    esac
  }
}

GetRequirements() {
  RequirePackage "git" && test -d $DOTCONF || git clone https://github.com/harsla/.conf $DOTCONF
}

AptUpdatedToday() {
  # won't work on darwin due to `stat` differences
  # but i guess you could use ruby there
  local stampFile=/var/lib/apt/periodic/update-success-stamp
  if [[ -f $stampFile ]]; then
    local stampstring=$(stat -c %y $stampFile)
    local stamp=$(date --date="$stampstring" +"%s")
    local now=$(date --date="$(date)" +"%s")
    local diff=$(echo "$now - $stamp" | bc)
    local aday=86400
    test $diff -lt $aday
  else
    return 1
  fi
}

UpdateAptRepositories() {
  echo "Updating apt repositories ... "
  DEBIAN_FRONTEND=noninteractive sudo apt-get update -qq
}

DeterminePlatform && UpdatePackageManagers && GetRequirements && case $PLATFORM in
  archlinux)
    BootstrapPlatform "archlinux"
    ;;
  ubuntu|raspbian)
    BootstrapPlatform "deb"
    ;;
  darwin)
    BootstrapPlatform "osx"
    ;;
  win)
    BootstrapPlatform "win"
    ;;
  wsl)
    BootstrapPlatform "deb"
    ;;
  *)
    echo "Unsupported platform!"
    ;;
esac
